/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ZB_DEVICE_PB_H_INCLUDED
#define PB_ZB_DEVICE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(8) ZbAttrCache_value_t;
/* Cached ZCL attribute value for a single attribute. */
typedef struct _ZbAttrCache {
    uint32_t attr_id; /* ZCL attribute ID */
    uint32_t data_type; /* ZCL data type byte */
    ZbAttrCache_value_t value; /* raw attribute value (nanopb: max_size:8) */
    uint32_t updated_ms; /* ESP32 tick time of last update */
} ZbAttrCache;

/* ZCL cluster with cached attribute values. */
typedef struct _ZbClusterCache {
    uint32_t cluster_id;
    pb_size_t attrs_count;
    ZbAttrCache attrs[8]; /* nanopb: max_count:8 */
} ZbClusterCache;

/* Single endpoint on a Zigbee device. */
typedef struct _ZbEndpoint {
    uint32_t ep_id;
    uint32_t profile_id;
    uint32_t device_id;
    pb_size_t clusters_count;
    ZbClusterCache clusters[16]; /* nanopb: max_count:16 */
} ZbEndpoint;

/* Complete device record — serialized as one .pb file per device. */
typedef struct _ZbDeviceRecord {
    uint64_t ieee_addr; /* 64-bit IEEE address (EUI-64) */
    uint32_t network_addr; /* 16-bit ZNP network address */
    pb_size_t endpoints_count;
    ZbEndpoint endpoints[8]; /* nanopb: max_count:8 */
    uint32_t last_seen_ms; /* ESP32 tick time of last communication */
} ZbDeviceRecord;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ZbAttrCache_init_default                 {0, 0, {0, {0}}, 0}
#define ZbClusterCache_init_default              {0, 0, {ZbAttrCache_init_default, ZbAttrCache_init_default, ZbAttrCache_init_default, ZbAttrCache_init_default, ZbAttrCache_init_default, ZbAttrCache_init_default, ZbAttrCache_init_default, ZbAttrCache_init_default}}
#define ZbEndpoint_init_default                  {0, 0, 0, 0, {ZbClusterCache_init_default, ZbClusterCache_init_default, ZbClusterCache_init_default, ZbClusterCache_init_default, ZbClusterCache_init_default, ZbClusterCache_init_default, ZbClusterCache_init_default, ZbClusterCache_init_default, ZbClusterCache_init_default, ZbClusterCache_init_default, ZbClusterCache_init_default, ZbClusterCache_init_default, ZbClusterCache_init_default, ZbClusterCache_init_default, ZbClusterCache_init_default, ZbClusterCache_init_default}}
#define ZbDeviceRecord_init_default              {0, 0, 0, {ZbEndpoint_init_default, ZbEndpoint_init_default, ZbEndpoint_init_default, ZbEndpoint_init_default, ZbEndpoint_init_default, ZbEndpoint_init_default, ZbEndpoint_init_default, ZbEndpoint_init_default}, 0}
#define ZbAttrCache_init_zero                    {0, 0, {0, {0}}, 0}
#define ZbClusterCache_init_zero                 {0, 0, {ZbAttrCache_init_zero, ZbAttrCache_init_zero, ZbAttrCache_init_zero, ZbAttrCache_init_zero, ZbAttrCache_init_zero, ZbAttrCache_init_zero, ZbAttrCache_init_zero, ZbAttrCache_init_zero}}
#define ZbEndpoint_init_zero                     {0, 0, 0, 0, {ZbClusterCache_init_zero, ZbClusterCache_init_zero, ZbClusterCache_init_zero, ZbClusterCache_init_zero, ZbClusterCache_init_zero, ZbClusterCache_init_zero, ZbClusterCache_init_zero, ZbClusterCache_init_zero, ZbClusterCache_init_zero, ZbClusterCache_init_zero, ZbClusterCache_init_zero, ZbClusterCache_init_zero, ZbClusterCache_init_zero, ZbClusterCache_init_zero, ZbClusterCache_init_zero, ZbClusterCache_init_zero}}
#define ZbDeviceRecord_init_zero                 {0, 0, 0, {ZbEndpoint_init_zero, ZbEndpoint_init_zero, ZbEndpoint_init_zero, ZbEndpoint_init_zero, ZbEndpoint_init_zero, ZbEndpoint_init_zero, ZbEndpoint_init_zero, ZbEndpoint_init_zero}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ZbAttrCache_attr_id_tag                  1
#define ZbAttrCache_data_type_tag                2
#define ZbAttrCache_value_tag                    3
#define ZbAttrCache_updated_ms_tag               4
#define ZbClusterCache_cluster_id_tag            1
#define ZbClusterCache_attrs_tag                 2
#define ZbEndpoint_ep_id_tag                     1
#define ZbEndpoint_profile_id_tag                2
#define ZbEndpoint_device_id_tag                 3
#define ZbEndpoint_clusters_tag                  4
#define ZbDeviceRecord_ieee_addr_tag             1
#define ZbDeviceRecord_network_addr_tag          2
#define ZbDeviceRecord_endpoints_tag             3
#define ZbDeviceRecord_last_seen_ms_tag          4

/* Struct field encoding specification for nanopb */
#define ZbAttrCache_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   attr_id,           1) \
X(a, STATIC,   SINGULAR, UINT32,   data_type,         2) \
X(a, STATIC,   SINGULAR, BYTES,    value,             3) \
X(a, STATIC,   SINGULAR, UINT32,   updated_ms,        4)
#define ZbAttrCache_CALLBACK NULL
#define ZbAttrCache_DEFAULT NULL

#define ZbClusterCache_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   cluster_id,        1) \
X(a, STATIC,   REPEATED, MESSAGE,  attrs,             2)
#define ZbClusterCache_CALLBACK NULL
#define ZbClusterCache_DEFAULT NULL
#define ZbClusterCache_attrs_MSGTYPE ZbAttrCache

#define ZbEndpoint_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ep_id,             1) \
X(a, STATIC,   SINGULAR, UINT32,   profile_id,        2) \
X(a, STATIC,   SINGULAR, UINT32,   device_id,         3) \
X(a, STATIC,   REPEATED, MESSAGE,  clusters,          4)
#define ZbEndpoint_CALLBACK NULL
#define ZbEndpoint_DEFAULT NULL
#define ZbEndpoint_clusters_MSGTYPE ZbClusterCache

#define ZbDeviceRecord_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   ieee_addr,         1) \
X(a, STATIC,   SINGULAR, UINT32,   network_addr,      2) \
X(a, STATIC,   REPEATED, MESSAGE,  endpoints,         3) \
X(a, STATIC,   SINGULAR, UINT32,   last_seen_ms,      4)
#define ZbDeviceRecord_CALLBACK NULL
#define ZbDeviceRecord_DEFAULT NULL
#define ZbDeviceRecord_endpoints_MSGTYPE ZbEndpoint

extern const pb_msgdesc_t ZbAttrCache_msg;
extern const pb_msgdesc_t ZbClusterCache_msg;
extern const pb_msgdesc_t ZbEndpoint_msg;
extern const pb_msgdesc_t ZbDeviceRecord_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ZbAttrCache_fields &ZbAttrCache_msg
#define ZbClusterCache_fields &ZbClusterCache_msg
#define ZbEndpoint_fields &ZbEndpoint_msg
#define ZbDeviceRecord_fields &ZbDeviceRecord_msg

/* Maximum encoded size of messages (where known) */
#define ZB_DEVICE_PB_H_MAX_SIZE                  ZbDeviceRecord_size
#define ZbAttrCache_size                         28
#define ZbClusterCache_size                      246
#define ZbDeviceRecord_size                      32063
#define ZbEndpoint_size                          4002

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
