/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "zb_device.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ZbAttrCache, ZbAttrCache, AUTO)


PB_BIND(ZbClusterCache, ZbClusterCache, AUTO)


PB_BIND(ZbEndpoint, ZbEndpoint, 2)


PB_BIND(ZbDeviceRecord, ZbDeviceRecord, 4)



